#!/bin/bash

if [ -z "$TODOFILE" ]
then
    echo_in_red "environment variable TODOFILE not set"
    exit 1
elif [ "$TODOROOT" == "" ]
then
    echo_in_red "environment variable TODOROOT not set"
    exit 1
else
    cd $TODOROOT
    echo "adding"
    git add $TODOFILE
    echo "committing"
    echo "git commit -m \"$*\""
    git commit -m "$*"
    cd -
fi
